brand:
  name: Teddy Rendahl
menu-string: Menu

nav:
  - title: Who
    url: '#who'
  - title: What
    url: '#what'
  - title: Where
    url: '#where'
  - title: Why
    url: '#portfolio'

copyright: Copyright &copy; Your Website 2018

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
